version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:latest
    container_name: laravel-app
    volumes:
      - ./www:/var/www/html
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
    working_dir: /var/www/html
    stdin_open: true
    tty: true
    networks:
      - laravel-network

  db:
    image: mariadb:10.11
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - laravel-network

  node:
    image: node:18
    container_name: node
    working_dir: /var/www/html
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./www:/var/www/html
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - laravel-network

volumes:
  db_data:

networks:
  laravel-network:

