version: '3.8'

services:
  web:
    build: .
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - laravel_network

  db:
    image: docker.io/mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: docker.io/phpmyadmin:5
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
